const { profile } = require("../../config/sequelizeDB");
const path = require('path');



module.exports = {

  uploadProfilePicture: async (userId, req, res, callback) => {
    try {
      const existingUser = await profile.findOne({ where: { user_id: userId } });
      if (!existingUser) {
        return res.status(404).json({ error: 'User not found' });
      }
  
      // Access the filename generated by Multer
      const filename = req.file.filename;
  
      // Update the user's profile picture path with the filename
      existingUser.profile_picture = filename;
      await existingUser.save();
  
      callback(null, existingUser);
    } catch (error) {
      console.error(error);
      callback({ error: 'Failed to update profile picture' }, null);
    }
  },

  getProfilePicture: (filename) => {
    const filePath = path.join(__dirname, '../../../uploads', filename);
    return filePath;
  }
}